In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [5]:
# Numpy 
# Importar o Numpy

import numpy as np

In [5]:
# Criando Arrays
help(np.array)

Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0,
          like=None)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
        If object is a scalar, a 0-dimensional array containing object is
        returned.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', '

In [6]:
# Array criado a partir de uma lista
vetor1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
print(vetor1)

[0 1 2 3 4 5 6 7 8 9]


In [8]:
type(vetor1)
# Um objeto do tipo ndarray é um recipiente multidimensional de itens do mesmo tipo e tamanho

numpy.ndarray

In [9]:
#Criando uma lista
lst = [0, 1, 2, 3, 4, 5, 6, 7, 8]

In [10]:
type(lst)

list

In [11]:
#Imprimindo na tela um valor específico
vetor1[0]

0

In [12]:
#Alterando um valor do array
vetor1[0] = 100

In [13]:
print(vetor1)

[100   1   2   3   4   5   6   7   8   9]


In [14]:
#Verificando o formato do array
print(vetor1.shape)

(10,)


In [15]:
#A função arange cria um vetor contendo uma progressão aritmética
# a partir de um intervalo -start, stop, step
vetor2 = np.arange(0., 4.5, .5)

In [16]:
#Verificando o tipo de objeto
type(vetor2)

numpy.ndarray

In [17]:
np.shape(vetor2)

(9,)

In [18]:
#Exibe o tipo de elementos que compõe o array
print(vetor2.dtype)

float64


In [19]:
# Cria um conjunto de numeros de 1 a 10 com intervalo 0.25
x = np.arange(1, 10, 0.25)
print (x)

[1.   1.25 1.5  1.75 2.   2.25 2.5  2.75 3.   3.25 3.5  3.75 4.   4.25
 4.5  4.75 5.   5.25 5.5  5.75 6.   6.25 6.5  6.75 7.   7.25 7.5  7.75
 8.   8.25 8.5  8.75 9.   9.25 9.5  9.75]


In [20]:
print(np.zeros(10))
#Metodo do numpy que monta um array de 10 elementos com zero

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [21]:
#Retorna 1 na posição diagonal e 0 nas restante
z = np.eye(3)


In [22]:
z

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
#Os valores passados como parametro, formam uma diagonal
d = np.diag(np.array([1, 2, 3, 4]))

In [25]:
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [26]:
    # Array de numeros complexos
    c = np.array([1+2j, 3+4j, 5+6*1j])

In [27]:
c

array([1.+2.j, 3.+4.j, 5.+6.j])

In [28]:
# Array de valores boleanos
b = np.array([True, False, False, True])

In [29]:
b

array([ True, False, False,  True])

In [30]:
#Array de strings
s = np.array(['Python', 'R', 'Ruby'])

In [31]:
s

array(['Python', 'R', 'Ruby'], dtype='<U6')

In [32]:
#O metodo Linspace (Linear spaced vector) retorna um numero de valores igualmente distribuidos 
#em um intervalo específico 
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
#CRIANDO UMA MATRIZ

In [33]:
# Para criar uma matriz
matriz = np.array([[1,2,3], [4,5,6]])

In [34]:
print(matriz)

[[1 2 3]
 [4 5 6]]


In [35]:
print(matriz.shape)

(2, 3)


In [36]:
#Criando uma matriz 2x3 com apenas numeros "1"
matriz1 = np.ones((2,3))

In [37]:
print(matriz1)

[[1. 1. 1.]
 [1. 1. 1.]]
